export { RELATORIO_TIPOS } from '@/entities/relatorio/model/types'
export type {
  ItemConsumo,
  ItemEstoqueMinimo,
  ItemProdutoCritico,
  ItemReposicao,
  ItemVencimento,
  MetricasMotorEstatistico,
  PrioridadeRelatorio,
  RelatorioConsumo,
  RelatorioEstoqueMinimo,
  RelatorioFiltro,
  RelatorioProdutosCriticos,
  RelatorioReposicao,
  RelatorioResultado,
  RelatorioTipo,
  RelatorioVencimentos,
  RiscoRelatorio,
  SeveridadeVencimento,
  StatusEstoqueRelatorio,
  StatusValidadeRelatorio,
  TendenciaConsumo,
  UrgenciaRelatorio,
} from '@/entities/relatorio/model/types'
export {
  prioridadeRelatorioLabel,
  prioridadeRelatorioTone,
  relatorioTipoLabel,
  riscoRelatorioLabel,
  riscoRelatorioTone,
  statusEstoqueRelatorioLabel,
  statusEstoqueRelatorioTone,
  statusValidadeRelatorioLabel,
  statusValidadeRelatorioTone,
  tendenciaConsumoLabel,
  tendenciaConsumoTone,
  urgenciaRelatorioLabel,
  urgenciaRelatorioTone,
} from '@/entities/relatorio/model/status'